server:
  port: 8765

spring:
  application:
    name: hello-spring-cloud-web-admin-feign
  zipkin:
    base-url: http://localhost:9411
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck.enable: true #开启健康检查
  instance:
    lease-renewal-interval-in-seconds: 3     #eureka client发送心跳给server端的频率。如果在leaseExpirationDurationInSeconds后，server端没有收到client的心跳，则将摘除该instance
    lease-expiration-duration-in-seconds: 6  #eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance

#Feign 是自带熔断器的，但默认是关闭的。需要在配置文件中配置打开它
feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        exclude: hystrix.stream  #访问/actuator/hystrix stream能看到不断更新的监控流